[package]
name = "snafu"
version = "0.1.1"
authors = ["Jake Goulding <jake.goulding@gmail.com>"]

readme = "README.md"
description = "An ergonomic error handling library"
documentation = "https://docs.rs/snafu"
repository = "https://github.com/shepmaster/snafu"

license = "MIT OR Apache-2.0"

keywords = ["error", "ergonomic", "library"]
categories = ["rust-patterns"]

[features]
default = ["rust_1_30"]

# New methods on `Error`; re-export of proc-macro
rust_1_30 = ["snafu-derive/rust_1_30"]

# The `snafu::display` attribute
unstable_display_attribute = ["snafu-derive/unstable_display_attribute"]

[workspace]
# The compatibility tests each set feature flags for the library and
# cannot be in the same crate graph.
exclude = [
  "compatibility-tests/nightly",
  "compatibility-tests/v1_30",
  "compatibility-tests/v1_18",
]

[dependencies]
snafu-derive = { path = "snafu-derive", version = "0.1.1" }
