[package]
name = "snafu-derive"
version = "0.1.0"
authors = ["Jake Goulding <jake.goulding@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = { version = "0.15.26", features = ["extra-traits", "full"] }
quote = "0.6.11"
proc-macro2 = "0.4.26"
