[package]
name = "basic"
version = "0.1.0"
authors = ["Jake Goulding <jake.goulding@gmail.com>"]
edition = "2018"

[dependencies]
snafu = { path = "../.." }
snafu-derive = { path = "../../snafu-derive" }
